version: '3.5'

services:
  db:
    image: postgres:15
    container_name: db_17_01_n8
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data_17_01_n8:/var/lib/postgresql/data/pgdata
    networks:
      - net_17_01_n8
    restart: always

  web:
    image: odoo:15
    container_name: odoo_17_01_n8
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data_17_01_n8:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - net_17_01_n8
    restart: always

networks:
  net_17_01_n8:
    name: net_17_01_n8

volumes:
  db_data_17_01_n8:
  odoo_data_17_01_n8: